### ISSUE TITLE
Getting Unhandled Exception on all platforms

### ISSUE THREAD

**Issue by Billyboii** [oamost/4sq2autogen4gmaps#4]
PS C:\Users\user\git\4sq2autogen4gmaps\build_output_win> .\4sq2autogen4gmaps.exe      
To get started, launch Authenticate.html

Paste client id:
ID_GOES_HERE

Paste client secret:
SECRET_GOES_HERE

Paste access code:
ACCESS_CODE_GOES_HERE

User input ready...
Obtaining access token...
Unhandled exception. System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at FsqAutogen.KmlGen.GetOauthAccessToken(UserInputModel input) in D:\a\4sq2autogen4gmaps\4sq2autogen4gmaps\src\modules\KmlGen.cs:line 90
   at FsqAutogen.KmlGen.ProcessCheckins() in D:\a\4sq2autogen4gmaps\4sq2autogen4gmaps\src\modules\KmlGen.cs:line 41
   at Program.Main(String[] args) in D:\a\4sq2autogen4gmaps\4sq2autogen4gmaps\src\Program.cs:line 10
   at Program.<Main>(String[] args)

Tested on MacOS, Linux, and Windows all getting the same result.

**Comment by banjaminlee** [comment]
https://bold.pro/my/banjamin-lee-241212153841

This is my resume.
I want to work with you.
I look forward your reply.

**Comment by oamost** [comment]
Hello @Billyboii, I was able to reproduce the issue you mentioned on Windows Server 2022, however, the reason for it might be that the access code you provided in your use-case was invalid. Here's a screenshot where in the URL bar you can spot that at the end of the partly highlighted access code, where the `#_=_` was not included, but that must also be included to make the tool work. 

Screenshot - bad access code copying:

![image](https://github.com/user-attachments/assets/2d540ce4-e244-4f35-b5a2-35f9f2eaa5f4)

Screenshot - good access code copying:

![image](https://github.com/user-attachments/assets/969ae98d-fd27-40c1-8b28-e0b728d70670)

There's one additional thing to note: the access code has a varying but relatively short lifespan and can expire, which could also 
lead to the exception above with the same stack trace.

I will add a more meaningful text print soon, so the user will know about these edge cases.

**Comment by oamost** [comment]
Edit: as visible on the following screenshot, a couple of minutes later, I checked the previously working access code, and it got expired, which led to the same exception with the same stack trace. As this can cause confusion on the user side, I will update the code to guide the user better in such cases.

![image](https://github.com/user-attachments/assets/8f6dedf5-71d2-465b-9038-b72a240da0fc)
